title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
#show_downloads: true
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
theme: jekyll-theme-cayman
